# KJShopPlus Configuration File

# Economy System
# Default currency symbol (Vault)
vault_display_symbol: "$"

# Custom currencies (CoinsEngine)
# The key (e.g., 'gems') MUST match the CoinsEngine currency ID.
custom_currencies:
  gems:
    display_name: "Gems "
  tokens:
    display_name: "Tokens "
  points:
    display_name: "Points "

# Dynamic Pricing
dynamic:
  enabled: true
  # How long before prices reset to base (in seconds)
  reset_interval_seconds: 3600 # 1 hour
  # Default formulas (can be overridden per-item)
  buy_formula: "default" # "default" = +1% per item
  sell_formula: "flat"  # "flat" = -0.1 per item

# Input Control (for Bedrock/Mobile support)
input_mode:
  left_tap_only: true
  disable_right_click: true
  disable_shift_click: true
  disable_inventory_drag: true
  tap_debounce_ms: 200

# Bedrock Compatibility (Geyser/Floodgate)
bedrock_compat:
  enabled: true
  force_button_actions: true
  material_map:
    PLAYER_HEAD: PAPER
    LIGHT: GLASS
    GRAY_STAINED_GLASS_PANE: BLACK_STAINED_GLASS_PANE
    LIME_WOOL: LIME_CONCRETE
    RED_WOOL: RED_CONCRETE

# Discord Webhook Logging
discord_logging:
  enabled: true
  webhooks:
    buy: "https://discord.com/api/webhooks/1431900825311248486/SMB-O4gweSqd7mZ0RypELhyxua5IoifPQRmzgWfAxrUAfEWGgd9V0GRfpvlIgozzHnhk"
    sell: "https://discord.com/api/webhooks/1431900925571895471/D5unj0SbjvWjQCBECkY-5w-KIXqfZENSAbiQk4WGPv-mbKD1SpNuwkD-BnmgvSBbjelS"
    admin: "https://discord.com/api/webhooks/1431900997340495943/NQuOfa2hvKSnAUNwQKPNenLzfmWG9m25Qp_9xTORGlphVVfwF2mm45YFKTQVRGq6DPbL"
    price_reset: "https://discord.com/api/webhooks/1431901057868632185/VHObQCRkPXxDhsrwRkeVKCQd9yxq4mHn_UtBGBmWpS-tfUKN9yAnm3OPYutsKACsr-LA"
  username: "KJShopPlus Bot"
  avatar_url: "https://cdn.discordapp.com/attachments/906913902267334698/1432420114195681452/download.jpg?ex=6900fcb0&is=68ffab30&hm=6f70d59af745156f10ef9eabe4647d761026576939905a69f4e432569bf3f8f7&"



