name: KJShopPlus
version: 1.0.0
main: xyz.kaijiieow.kjshopplus.KJShopPlus
api-version: '1.21' # Target 1.21 API
softdepend: [Vault, CoinsEngine, Geyser-Spigot, floodgate]

commands:
  # Main shop command for players
  shop:
    description: "Opens the main KJShopPlus GUI"
    aliases: [kshop, kjshop] # Common aliases
    permission: kjshopplus.user.open # Permission required to open the shop
    permission-message: "You don't have permission to use the shop."

  # Admin command
  kjshopadmin:
    description: "Admin commands for KJShopPlus"
    aliases: [sa, kjsa] # Short aliases for admin
    permission: kjshopplus.admin # Base admin permission (specific subcommands need sub-permissions)
    permission-message: "You don't have permission to use admin commands."
    usage: "/<command> [reload|resetprices|help]" # Basic usage info

permissions:
  kjshopplus.user.open:
    description: Allows players to open the shop GUI using /shop.
    default: true # Allow everyone to open by default
  kjshopplus.admin:
    description: Base permission node for admin commands.
    default: op # Only OPs have admin access by default
    children:
      kjshopplus.admin.reload: true
      kjshopplus.admin.resetprices: true
      # kjshopplus.admin.edit: true # Example for future edit commands

  kjshopplus.admin.reload:
    description: Allows reloading the plugin configuration.
    default: op
  kjshopplus.admin.resetprices:
    description: Allows manually resetting dynamic prices.
    default: op

